#define MARGINHEALTHBARX	1100
#define MARGINHEALTHBARY	10
#define MARGINHEALTHBARH	400
#define MARGINHEALTHBARW	50	

#define INNERHEALTHBARX		1106	
#define INNERHEALTHBARY		16	
#define INNERHEALTHBARH		390	
#define INNERHEALTHBARW		40	
