#ifndef INFO_COMPONENTS_H_
#define INFO_COMPONENTS_H_

#define MARGINHEALTHBARX	1100
#define MARGINHEALTHBARY	10
#define MARGINHEALTHBARH	400
#define MARGINHEALTHBARW	50	

#define INNERHEALTHBARX		1106	
#define INNERHEALTHBARY		16	
#define INNERHEALTHBARH		390	
#define INNERHEALTHBARW		40	


#define MARGINLASERBARX		1100
#define MARGINLASERBARY		410
#define MARGINLASERBARH		150
#define MARGINLASERBARW		50	

#define INNERLASERBARX		1106	
#define INNERLASERBARY		416	
#define INNERLASERBARH		140	
#define INNERLASERBARW		40	

#endif
